-- Esquema propio de UTU. No utiliza ni modifica la base mercopan del producto anterior.
CREATE TABLE IF NOT EXISTS personas (
 id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE,
 activo TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS proveedores (
 id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE,
 telefono VARCHAR(40) NOT NULL DEFAULT '', activo TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS ingredientes (
 id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE,
 unidad ENUM('kg','l','unidad') NOT NULL, stock DECIMAL(12,3) NOT NULL DEFAULT 0,
 minimo DECIMAL(12,3) NOT NULL DEFAULT 0, activo TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS historial (
 id INT AUTO_INCREMENT PRIMARY KEY, fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 persona_id INT NOT NULL, persona_nombre VARCHAR(100) NOT NULL,
 modulo VARCHAR(40) NOT NULL, detalle VARCHAR(500) NOT NULL,
 FOREIGN KEY (persona_id) REFERENCES personas(id)
) ENGINE=InnoDB;
