CREATE TABLE IF NOT EXISTS productos (
 id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE,
 unidad ENUM('kg','unidad') NOT NULL, precio DECIMAL(12,2) NOT NULL,
 stock DECIMAL(12,3) NOT NULL DEFAULT 0, activo TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;
